### ISSUE TITLE
Feature Request: sqlcommenter support?

### ISSUE THREAD

**Issue by StevenACoffman** [XSAM/otelsql#109]
I read that [Sqlcommenter merged into OpenTelemetry](https://cloud.google.com/blog/products/databases/sqlcommenter-merges-with-opentelemetry).

I have database connection code that I have already instrumented with https://github.com/XSAM/otelsql
```
	wrappedDriverName, err := otelsql.Register(
		"pgx",
		semconv.DBSystemPostgreSQL.Value.AsString(),
	)
```
and I am wondering if adding [sqlcomment](https://github.com/ariga/sqlcomment) is redundant or if it would provide additional value?

**Comment by XSAM** [comment]
I am not familiar with the sqlcomment, but as long as it instruments the database via injecting codes into `database/sql`, which it is, they are pretty much doing the same thing.

**Comment by XSAM** [comment]
@StevenACoffman This is an interesting feature 👍. I created a [PR](https://github.com/XSAM/otelsql/pull/112) to implement this. PTAL.

**Comment by StevenACoffman** [comment]
Thanks! Very cool!
