### ISSUE TITLE
Truncate attribute value to a given length

### ISSUE THREAD

**Issue by bogdanrudka-nix** [XSAM/otelsql#110]
Hey, I'm appreciating the work being done on this instrumentation. Our project is looking forward to using this instrumentation for DB monitoring, as it provides so needed customizability. 
We are using NewRelic as our main monitoring system. And we have a little problem monitoring DB with otel. NewRelic limits its attribute length to 4096 characters and if an attribute is longer than that, it will drop the span. As a result, it drops some long queries. It would be nice to have an option in the client that truncates any attribute values that are longer than a given size.

**Comment by XSAM** [comment]
I am not sure about this feature.

Using an opentelemetry collector as a spans processor to truncate attributes seems a good alternative. This approach could be a global processor; thus, no need to change every library.

**Comment by bogdanrudka-nix** [comment]
Thanks for your reply! 
After further investigation in the direction, you suggested I found that this feature is already implemented. To truncate long attributes we need to set a variable `OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT `
