### ISSUE TITLE
Incompatible with go.opentelemetry.io/otel/metric v0.35.0

### ISSUE THREAD

**Issue by hairyhenderson** [XSAM/otelsql#138]
### Description

When upgrading an application's dependency `go.opentelemetry.io/otel/metric` to v0.35.0, this module fails to compile. I see that this PR removed some packages that are used here: https://github.com/open-telemetry/opentelemetry-go/pull/3530

### Environment

- OS: n/a
- Architecture: n/a
- Go Version: n/a
- otelsql version: v0.17.1

### Steps To Reproduce

1. See https://github.com/XSAM/otelsql/pull/137, for example

### Expected behavior

`otelsql` should compile

**Comment by XSAM** [comment]
Thank you @hairyhenderson for raising this issue.

I have upgraded the `otel` library. Please check https://github.com/XSAM/otelsql/releases/tag/v0.18.0

**Comment by hairyhenderson** [comment]
Awesome! thanks @XSAM 🙇‍♂️
