### ISSUE TITLE
Oracle connection string

### ISSUE THREAD

**Issue by CongSon** [XSAM/otelsql#144]
With your example, init mysql database connection with these code:
`
db, err := otelsql.Open("mysql", mysqlDSN, otelsql.WithAttributes(
		semconv.DBSystemMySQL,
	))
`
i think with oracle, init database will be:
`
db, err := otelsql.Open("oracle", oracleDSN, otelsql.WithAttributes(
		semconv.DBSystemOracle,
	))
`
i dont know with oracle, what will connection string "oracleDSN" look like? please guide me. Thanks a lot!

**Comment by XSAM** [comment]
Hi @CongSon, the driver name and the DSN is up to the implementation of the driver, not the `dashbase/sql` or the `otelsql`.

Take [`go-sql-driver`](https://github.com/go-sql-driver/mysql) as an example, it has a section describing its DSN format. https://github.com/go-sql-driver/mysql#dsn-data-source-name

If you'd like to connect to oracle, make sure to check the driver name and the DSN format of that certain oracle driver.

**Comment by CongSon** [comment]
Thanks @XSAM . i'm totally understand!!!
