### ISSUE TITLE
Bug with new version otel v1.14.0

### ISSUE THREAD

**Issue by naofel1** [XSAM/otelsql#151]
### Description

There are a problem with the WithUnit instrument method, with the new release 1.14.0 Otel remove the Unit package and change the Unit type by string. 

Deprecated
 The go.opentelemetry.io/otel/metric/unit package is deprecated.
 - Use the equivalent unit string instead. (https://github.com/open-telemetry/opentelemetry-go/pull/3776)
 - Use "1" instead of unit.Dimensionless
 - Use "By" instead of unit.Bytes
 - Use "ms" instead of unit.Milliseconds

### Environment

- Go Version: 1.19
- otelsql version: v1.14

### Steps To Reproduce
```sh
go run cmd/main.go
# github.com/XSAM/otelsql
../../../go/pkg/mod/github.com/!x!s!a!m/otelsql@v0.19.0/instruments.go:52:23: cannot use unit.Milliseconds (constant "ms" of type unit.Unit) as type string in argument to instrument.WithUnit
../../../go/pkg/mod/github.com/!x!s!a!m/otelsql@v0.19.0/instruments.go:88:23: cannot use unit.Milliseconds (constant "ms" of type unit.Unit) as type string in argument to instrument.WithUnit
```

**Comment by XSAM** [comment]
The [v0.20.0](https://github.com/XSAM/otelsql/releases/tag/v0.20.0) has been released. Please check.

**Comment by naofel1** [comment]
Nice, the new release fix the issue. Thanks @XSAM ✨
