### ISSUE TITLE
Method of partially enabling this 

### ISSUE THREAD

**Issue by fantapop** [XSAM/otelsql#169]
### Problem Statement

I'd like to introduce otelsql tracing to a large code base.  The problem is that our model layer doesn't currently plumb the context into it.  Without the parent context, the tracing spans created in otelsql are orphaned.  I'd like to be able to enable the library but only have it create tracing spans when there is a valid parent trace.  This will make it easier to introduce this overtime.

### Proposed Solution

A new configuration option that enables this behavior could be used.  I've implemented this in a fork and it seems to work.   https://github.com/fantapop/otelsql/commit/ae9438eec4059c4517784a11e786b6b768874ee0  
Let me know what you think.  I could also just use the fork until such a time that we're ready to switch back to the original library.

#### Alternatives

A couple other alternatives I consider were to:
1) check the configuration option before any span is created and bypass it
2) allow a more generalized configuration function that could be customized to determine whether a span should be opened or not.  

#### Prior Art

I was looking bug reports to see if there were other requests for this.  I found this similar thing but it ended up being not quite what I wanted: https://github.com/XSAM/otelsql/pull/116/files#diff-0e426a43248661127a0c0ee115aef7a1093b635f8993b3f7ebb1dd9f05b8f249R125

**Comment by XSAM** [comment]
Thanks for raising this issue. I think adding `OmitSpan` function like `SpanNameFormatter` is good, so end-users can use their logic to omit spans.

---

Similar to #96, but not the same.

**Comment by XSAM** [comment]
> thanks for your response here. I can put together a PR. What are your thoughts on using the NoOp Span inside `createSpan` vs sprinkling conditionals throughout the code to bypass calling of `createSpan` altogether?

I personally prefer bypassing the calling of `createSpan`

---

A function from end-users, says `OmitSpan`, should not affect the functionality of other options like `OmitConnPrepare`. Having `DefaultOmitSpan` might break that. Though it is good to use a single function to wrap all the omitting behavior for cleanness.
