### ISSUE TITLE
root spans created without existing spans

### ISSUE THREAD

**Issue by inigohu** [XSAM/otelsql#179]
### Description

There was an issue https://github.com/XSAM/otelsql/issues/7 about creating multiple `sql.conn.reset_session` spans when pinging the database. The fix came with the PR https://github.com/XSAM/otelsql/pull/13, but the PR https://github.com/XSAM/otelsql/pull/101 removes the `trace.SpanContextFromContext(ctx).IsValid()` check.

### Environment

- otelsql version: v0.23.0

### Steps To Reproduce

1. Exec `db.PingContext(ctx)` in your application with an instrumented database client using otelsql

### Expected behavior

Avoid creating `sql.conn.reset_session` with each ping to the database.

**Comment by XSAM** [comment]
@inigohu Thank you for raising this issue.

It sounds like we need to bring an option like `PreventOrphan`, a reversed `AllowRoot` option, again.

BTW, if you only want to avoid creating `sql.conn.reset_session` spans, you can use the `SpanFilter` option to filter such spans out.

---

Is the `SpanFilter` option fit your need? Or an option like `PreventOrphan` is what you are looking for?

**Comment by inigohu** [comment]
Hi @XSAM ,

I didn't see the `SpanFilter` option. This definitely solves our need. Thank you very much.
