### ISSUE TITLE
Features not toggleable in config? 

### ISSUE THREAD

**Issue by brphelps** [XSAM/otelsql#22]
### Problem Statement
I see a list of features (some described as on by default) -- I'm trying to disable all features that write out the full query text of the executed query. Is there a way I can currently do that? 

### Proposed Solution

SpanOptions or something like it would support a "WriteQueryStatement" arg.

#### Alternatives

It seems like there is a way to configure some things, maybe I am overlooking how to disable these other spans?

**Comment by XSAM** [comment]
Sorry about the confusing description of "Enabled by default", which actually means it is a feature that can't be disabled. I can fix that confusing description in the next updates.

Interestingly, the [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#call-level-attributes) is now claiming the `db.statement` is not a required attribute anymore.

I can try to add a config, maybe called `Query`, to disable this feature. That will stop populating the `db.statement` attribute.
