### ISSUE TITLE
driver: skip fast-path; continue as if unimplemented

### ISSUE THREAD

**Issue by piclemx** [XSAM/otelsql#353]
### Description

Hello, I did move some of our application from opentracing to opentelemetry. I did use this library for instrumenting our DB part.

We are getting this error on a trace. The app doesn't seem to show any errors, only one span that's mark as error.

```
driver: skip fast-path; continue as if unimplemented
```
Happening on this `sql.conn.query`

### Environment

- OS: Mac OSx
- Architecture: [e.g. x86, i386]
- Go Version: 1.22
- otelsql version: v0.33.0

### Steps To Reproduce

1. Use the configuration mysql driver with the version 1.8.1
2. Run '...'
3. See error

### Expected behavior

I would have expected that the span would not make as an error.

**Comment by XSAM** [comment]
Hi @piclemx, thanks for raising this issue.

It seems like you can use the `DisableErrSkip` flag from [SpanOptions](https://pkg.go.dev/github.com/XSAM/otelsql#SpanOptions) to solve this situation.

**Comment by piclemx** [comment]
@XSAM Would this hide any errors that the driver will be showing? I'm just trying to understand if we might miss something by disabling this.

**Comment by XSAM** [comment]
https://github.com/XSAM/otelsql/blob/ccf8e55d800f965ff340a8e32dfdcb0bf6e03125/utils.go#L41-L52

It only hides `driver.ErrSkip`.

**Comment by piclemx** [comment]
Yep, that works well thanks!
