### ISSUE TITLE
Issue with DSN parsing when using with Databricks SQL Driver

### ISSUE THREAD

**Issue by nverkhachoyan** [XSAM/otelsql#358]
### Description

It looks like otelsql is passing an empty string as the DSN when calling sql.Open(driverName, ""). As a result, the Databricks SQL driver isn’t getting the proper DSN it needs to parse, which leads to the following error:

```
request error: invalid DSN: invalid DSN port: strconv.Atoi: parsing "": invalid syntax
```

The otelsql [code](https://github.com/XSAM/otelsql/blob/f079f7590a0c3567ae3ce15f5bb38f11c11aae41/sql.go#L80) that makes the function call

```go
db, err := sql.Open(driverName, "")
if err != nil {
    return "", err
}
```

And the Databricks SQL Driver [code](https://github.com/databricks/databricks-sql-go/blob/0ddea3730ba688650e9fb46e521e079267e726cd/driver.go#L33) that attempts to parse it.

```go
func (d *databricksDriver) OpenConnector(dsn string) (driver.Connector, error) {
	ucfg, err := config.ParseDSN(dsn)
	if err != nil {
		return nil, err
	}
	return NewConnector(withUserConfig(ucfg))
}
```

### Environment

- Go Version: v1.22.5
- otelsql version: v0.33.0
- Databricks SQL Go v1.6.1

### Steps To Reproduce

The simple code snippet below is enough to reproduce the error. 

```Go
package main

import (
	"fmt"
	"os"

	"github.com/XSAM/otelsql"
	_ "github.com/databricks/databricks-sql-go"
	"go.opentelemetry.io/otel/attribute"
)

func main() {
	dsn := os.Getenv("DATABRICKS_DSN")

	db, err := otelsql.Open("databricks", dsn, otelsql.WithAttributes(
		attribute.String("db.system", "databricks"),
	), otelsql.WithSpanOptions(otelsql.SpanOptions{
		DisableQuery: true,
	}))
	if err != nil {
		fmt.Printf("error database connection: %v\n", err)
		return
	}

	var id int
	err = db.QueryRow("SELECT 1").Scan(&id)
	if err != nil {
		fmt.Printf("failed to fetch database: %v\n", err)
		return
	}

	fmt.Printf("Database responded: %v\n", id)
}
```

### Expected behavior

The Databricks driver should properly receive and parse the DSN string, and the opened connection should be wrapped with otelsql. 

### Actual behavior 

Returns an invalid DSN error
```
request error: invalid DSN: invalid DSN port: strconv.Atoi: parsing "": invalid syntax
```

**Comment by XSAM** [comment]
Hi @nverkhachoyan, thanks for raising this issue.

`otelsql` does not wrap the `sql.DB` (at least for the current implementation). So `otelsql.Open` uses `sql.Open` to only get the driver.

https://github.com/XSAM/otelsql/blob/f079f7590a0c3567ae3ce15f5bb38f11c11aae41/sql.go#L78-L87

There is a potential way that I can try to pass the DSN to the `sql.Open` even though `otelsql` does not use it to actually open a connection. But, I need to run some tests to verify this.

Before that, you can use [`otelsq.WrapDriver`](https://pkg.go.dev/github.com/XSAM/otelsql#WrapDriver) method to bypass this issue. Example: https://pkg.go.dev/github.com/XSAM/otelsql#example-WrapDriver

```go
db, err := sql.Open("databricks", dsn)

otDriver := otelsql.WrapDriver(dri)

connector, err := otDriver.(driver.DriverContext).OpenConnector(mysqlDSN)
if err != nil {
	panic(err)
}

// Connect to database
db = sql.OpenDB(connector)
defer db.Close()
```

**Comment by XSAM** [comment]
@nverkhachoyan I have made a release that includes the fix. https://github.com/XSAM/otelsql/releases/tag/v0.34.0

You can now use `otelsql.Open` with Databricks SQL Driver.
