### ISSUE TITLE
Database connection contention spans

### ISSUE THREAD

**Issue by glerchundi** [XSAM/otelsql#36]
### Problem Statement

We're conducting a performance testing and we saw that most of the time is consumed in between the API call and the actual query.

We don't know yet where the problem is but we have two suspicions:
1. The database is rate limiting or taking more time to connect due to this contention.
2. There is a limit in the `database/sql` and the pool is locking the current query until another connection is released.

### Proposed Solution

Add more spans to the driver so that it also registers traces for the connection opening times as well as internal locking times. I don't know if it's even possible. 

#### Alternatives

Logging :D

**Comment by rajeshkarnena** [comment]
Hi @XSAM, 

We also have a similar connection contention issue where there's some delay to acquire a connection. If you look at the sample trace attached below, we see that there's some unknown wait time which we are assuming that is the time to acquire a connection. 

<img width="702" alt="Screenshot 2022-02-21 at 14 00 16" src="https://user-images.githubusercontent.com/12097272/158468388-6a501fc0-53c1-4f98-921d-5daf46403cb4.png">

I was thinking that adding a span at this [connect method](https://github.com/XSAM/otelsql/blob/main/connector.go#L36) might give us some better insights on the time taken for acquiring a connection.   

Please correct me if I am wrong. Happy to raise a PR :)

Thanks!

**Comment by XSAM** [comment]
> I was thinking that adding a span at this [connect method](https://github.com/XSAM/otelsql/blob/main/connector.go#L36) might give us some better insights on the time taken for acquiring a connection.

@rajeshkarnena You are right. Adding a span at connect method can give better insights.

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/11306772/158528893-43ecc0a5-56fa-4e0c-9e81-71c26023eb82.png">

Are you interested in implementing this? If so, I can assign this issue to you.

**Comment by rajeshkarnena** [comment]
Hi @XSAM, yes I'm interested. Please assign this to me :)
