### ISSUE TITLE
Is there a way to specify read-only connection?

### ISSUE THREAD

**Issue by paras-blacklane** [XSAM/otelsql#364]
### Description

It would be nice to have a way to connect to a database in read-only mode. Maybe there's a way already, i didn't find it in the docs

**Comment by paras-blacklane** [comment]
Can't seem to remove the `bug` label

**Comment by XSAM** [comment]
> It would be nice to have a way to connect to a database in read-only mode.

I am not sure what is a read-only mode regarding `database/sql`. If you want to ensure no write operation can be made to the database through the connection, you should configure the permission of the database user.

**Comment by paras-blacklane** [comment]
Something analogous to [setting session characteristics in postgres](https://www.postgresql.org/docs/15/sql-set-transaction.html) would be useful. Yea there's always that option for creating a read-only user. But i needed this for something

**Comment by XSAM** [comment]
It seems like a db operation. Whether to have this feature is out of the scope of otelsql, as it is a wrapper to monitor the DB operations, not a driver that implements the functionality.

Assuming you are using a DB driver that supports functionality with database/sql interfaces, then otelsql should also support this feature.

**Comment by paras-blacklane** [comment]
Sure, i will find it in the postgres lib then. Will close the issue
