### ISSUE TITLE
current implementation will skip request if the driver does not implement `driver.ExecerContext`

### ISSUE THREAD

**Issue by cuichenli** [XSAM/otelsql#390]
### Description

The current implementation does not support drivers that do not implement the `driver.ExecerContext` interface,  such as [sqlserver driver](https://github.com/denisenkom/go-mssqldb).

At present, the `ExecContext` function checks whether the driver implements the `driver.ExecerContext` interface. If the driver does not implement this interface, the request is skipped.

https://github.com/XSAM/otelsql/blob/e9f8e31a8621f2e1794ad665e6cefa129fdc1b3e/conn.go#L92-L95

However, this `go-mssqldb` does not implement the interface https://pkg.go.dev/github.com/denisenkom/go-mssqldb#Conn
And in such a case, if my understanding is correct, the request would not be executed at all. Given that `ExecerContext` is an optional interface, it is reasonable for some implementations to omit it. The documentation outlines a fallback mechanism: 

>If a [Conn](https://pkg.go.dev/database/sql/driver#Conn) does not implement [ExecerContext](https://pkg.go.dev/database/sql/driver#ExecerContext), the [database/sql.DB.Exec](https://pkg.go.dev/database/sql#DB.Exec) will fall back to [Execer](https://pkg.go.dev/database/sql/driver#Execer); if the Conn does not implement Execer either, [database/sql.DB.Exec](https://pkg.go.dev/database/sql#DB.Exec) will first prepare a query, execute the statement, and then close the statement.

Given this fallback mechanism and our goal to enhance observability, I think it makes more sense to fall back to use [database/sql.DB.Prepare](https://pkg.go.dev/database/sql#DB.Prepare) to create a statement, and then try to invoke the [database/sql.Stmt.ExecContext](https://pkg.go.dev/database/sql#Stmt.ExecContext) function. If this approach also fails, we should follow the fallback procedures outlined in the official documentation. But of course, the fallback I provided is based on the implementation of sqlserver driver.

Please let me know if there are any inaccuracies in my understanding. Thank you!

**Comment by XSAM** [comment]
Hi @cuichenli, thanks for raising this issue.

Though it is not a big difference, I want to point out that the `sqlserver driver` you mentioned, https://github.com/denisenkom/go-mssqldb, is no longer maintained. 

We should check its successor instead: https://github.com/microsoft/go-mssqldb

---

Regarding your concern about being incompatible with the `go-mssqldb`, I am not sure I understand the reason that could cause the incompatible issue.

The implementation of `DB.execDC` has a built-in fallback mechanism, which has been used in https://pkg.go.dev/database/sql#DB.ExecContext and https://pkg.go.dev/database/sql#Conn.ExecContext

Here is the code: https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/database/sql/sql.go;l=1688-1725

With this built-in fallback mechanism, I am not sure we need to implement an additional fallback on our own.

---

I would also suggest https://github.com/microsoft/go-mssqldb library should implement https://pkg.go.dev/database/sql/driver#ExecerContext, as https://pkg.go.dev/database/sql/driver#Execer is a deprecated interface.

After all, distributed tracing does not help a lot when context propagation is not available.

**Comment by cuichenli** [comment]
I have reviewed the source code again. The request is not being skipped; rather, it is processed through the `Stmt` mechanism. The SQL driver does not implement either `Execer` or `ExecerContext`.


The code you referenced is actually checking the implementation of `otConn` instead of the `Conn` type that `otConn` wraps. Since `otConn` implements the `ExecContext` interface, it will call the `otConn.ExecContext` function. Within this function, it checks the implementation of the `Conn` from the SQL driver, which might lead to a fallback to ErrSkip.


The requests are actually sent via the Stmt interface at [source link](https://cs.opensource.google/go/go/+/refs/tags/go1.23.4:src/database/sql/sql.go;l=1717).


Since the requests are not skipped, I am closing this issue. Apologies for the false alarm.
