### ISSUE TITLE
Opening lots of connections uses up all available slots

### ISSUE THREAD

**Issue by rcrowe** [XSAM/otelsql#72]
### Description

```
{"error":"failed to register otel driver: unable to register driver, all slots have been taken","level":"warning","msg":"Failed indexing, retrying in 30s","time":"2022-03-23T11:38:21Z"}
```

We have a service that opens a number of connections inside a backoff, correctly closing a connection before opening a new one. However, the stdlib doesn't offer a Unregister method for an SQL driver, which means each time we are opening a new connection with otelsql we are taking up a new slot. Eventually we run out without restarting the service.

https://pkg.go.dev/database/sql#OpenDB looks to be exactly what I'm after, specifically...
> OpenDB opens a database using a Connector, allowing drivers to bypass a string based data source name.

### Environment

- OS: k8s
- Architecture: x86
- Go Version: [e.g. 1.18]
- otelsql version: 1.12

### Steps To Reproduce

I can create an example if helpful, but it's effectively a for loop that is greater than `>maxDriverSlot` where a connection is opened & then closed. 

### Expected behaviour

`otelsql` to implement the [Connector](https://pkg.go.dev/database/sql/driver#Connector) driver so that OpenDB can be used.

**Comment by rcrowe** [comment]
Seems I overlooked https://github.com/XSAM/otelsql/blob/b04958384c12547827023dd26753907eef374c5b/driver.go#L47

**Comment by rcrowe** [comment]
Instead of just closing this, thought it best to share the solution I found to my problem.

Using the `pgx` library for example (we use it for both postgres & cockroachdb, hence dbidentifier)...
```
driverctx, ok := otelsql.WrapDriver(stdlib.GetDefaultDriver(), o.dbidentifier).(driver.DriverContext)
if !ok {
	return nil, errors.New("failed to create driver ctx from otel driver")
}

otelsqlConnector, err := driverctx.OpenConnector(stdlib.RegisterConnConfig(connConfig))
if err != nil {
	return nil, fmt.Errorf("failed to create connector from otel driver: %w", err)
}

sqlDB := sql.OpenDB(otelsqlConnector)
if o.openPing {
	if err := sqlDB.Ping(); err != nil {
		_ = sqlDB.Close()
		return nil, fmt.Errorf("failed to connect to the database: %w", err)
	}
}
```

@XSAM Does this look correct to you, and would it be worth including in an example?

Feel free to close the issue.

**Comment by XSAM** [comment]
> Does this look correct to you, and would it be worth including in an example?

Yeah, it looks good. I can try to include this in examples. Thanks for providing the use case.

Besides, I can add `otelsql.OpenDB` for `sql.OpenDB`, making this more intuitive.
