### ISSUE TITLE
Spans named after corresponding methods make graph too busy

### ISSUE THREAD

**Issue by mostafafarzaneh** [XSAM/otelsql#97]
I am using `otelsql` to send traces to AWS X-RAY through opentelemetry.
In the X-RAY console I see seperate nodes for each methods. For example I see seperate nodes for `sql.conn.reset_session`, `sql.conn.prepare`, `sql.conn.reset_session`, `sql.stmt.query`, and `sql.rows`. 
What I am looking after is for X-RAY to create one node with a given name that has multiple spans. But when using different names for each method the graph became too busy.

**Comment by XSAM** [comment]
It seems related to https://github.com/XSAM/otelsql/issues/57.

**Comment by mostafafarzaneh** [comment]
It is close to #57.
What I wanted is to set the name of the span fixed regardless of what method has been called. I believe it is what [uptrace](github.com/uptrace/opentelemetry-go-extra/otelsql) is doing.

**Comment by mostafafarzaneh** [comment]
Thanks, 
It worked just as I expected.

I have another question. Is there any way to attach the method name to the span to distinguish each span? Currently, I cannot distinguish between `query` and `prepare` methods. Is there any way to add metadata or annotation to the spans?

**Comment by XSAM** [comment]
I think that is the purpose of span name, to give you a clear distinguish.

**Comment by mostafafarzaneh** [comment]
After digging into `awsxrayexporter` found out that AWS expects the database name to be present in `DBNameKey`. [Here](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/471b2fba9dd0786c288029100404ae3206793113/exporter/awsxrayexporter/internal/translator/segment.go#L145)!

So, In my specific case which I am using X-Ray, I no longer need to use [`otelsql.WithSpanNameFormatter`](https://pkg.go.dev/github.com/XSAM/otelsql#WithSpanNameFormatter). Instead the below snippets helped me set the node name.

>>>
	sql, err := otelsql.Open("mysql", URL,
		otelsql.WithAttributes(semconv.DBSystemMySQL,
			semconv.DBConnectionStringKey.String(URL)),
			semconv.DBNameKey.String("my-db-name")))// X-Ray expect database name in db.name

I close the issue because I think it is the X-Ray exporter's job to grab the method from the span name and put it into the metadata.
