### ISSUE TITLE
Access to the underlying connection when using `WrapDriver`

### ISSUE THREAD

**Issue by nick-kentik** [XSAM/otelsql#98]
### Problem Statement

[`database/sql.Conn#Raw()`](https://pkg.go.dev/database/sql#Conn.Raw) allows us to get the underlying driver's connection. We use this in some existing code to get a `*pgx.Conn` for `CopyFrom` functionality (via [`pgx/v4/stdlib.Conn#Conn()`](https://pkg.go.dev/github.com/jackc/pgx/v4/stdlib#Conn)).

However, when using `otelsql.WrapDriver`, `Raw()` yields an `*otelsql.otConn` instead of a `*pgx/v4/stdlib.Conn`. That has a *field* `Conn`, set to the `*pgx/v4/stdlib.Conn`, but since `otConn` isn't exported, I can't do a type assertion on it to get the underlying connection - if I want to do `CopyFrom`, I have to resort to `reflect`, which I'd rather not do.

Going to the underlying connection bypasses telemetry for that specific call, which is non-optimal, but being able to introduce observability into the rest of the application would still be a win :sweat_smile:

### Proposed Solution

Add this to `conn.go`:

```go
func (o *otConn) Conn() driver.Conn {
    return o.Conn
}
```

(well, sort of, the `Conn` field would need to be renamed).

I can then declare an interface to get it instead of using `reflect`:

```go
type Conner interface {
    Conn() driver.Conn
}

conn.Raw(func(driverConn interface{}) error {
	if c, ok := driverConn.(Conner) {
		pc := c.Conn().(*stdlib_pgx.Conn).Conn() // yuck, but no reflect
		fmt.Printf("%T\n", pc)
        }
})
```

#### Alternatives

There's a few possiblities; ideally, that `Raw` call would never return the `otConn`, but I don't know if that's possible.

We could export the `otConn` type so type assertions are possible.

We could implement `Raw` on the `otConn` in some way?

We could make `CopyFrom` available in some other way. It's actually `*pgx.Tx#CopyFrom` that I'm after in the end, but I saw no reasonable way to go from the `otTx` to a `*pgx.Tx`

#### Prior Art

?

### Additional Context

This is actually a conversion from `instrumentedsql` to `otelsql`. The former had the same issue, but we just forked it internally and made a commit that exported the connection type. I'd rather not do that again with an active project :sweat_smile: .

**Comment by nick-kentik** [comment]
Here's a fragment of the current code, using `reflect` to get to the `*pgx.Conn`, that I'm trying to avoid :sweat_smile: . I can develop it into a `main.go` if you need it to be self-contained.

```go
import (
	"context"
	"reflect"

	pgx "github.com/jackc/pgx/v4"
	stdlib_pgx "github.com/jackc/pgx/v4/stdlib"
)

// set up db
conn, _ := db.Conn(context.Background())

_ = conn.Raw(func(driverConn interface{}) error {
	// If otelsql isn't in place, we'll have a *stdlib_pgx.Conn
	if c, ok := driverConn.(*stdlib_pgx.Conn); ok {
		// Without otelsql, c.Conn() is a *pgx.Conn
		fmt.Printf("%T\n", c)
		return nil
	}

	// If this is an *otelsql.otConn, use reflect to get the underlying conn
	underlying := reflect.Indirect(reflect.ValueOf(driverConn))
	if underlying.Kind() == reflect.Struct {
		connValue := underlying.FieldByName("Conn")
			if connValue.IsValid() {
				if c, ok := connValue.Interface().(*stdlib_pgx.Conn); ok {
					// c.Conn() is a *pgx.Conn
					fmt.Printf("%T\n", c)
					return nil
				}
			}
		}

	return fmt.Errorf("Couldn't convert a %T into a *pgx.Conn", driverConn)
})
```

**Comment by XSAM** [comment]
@nick-kentik Thank you for submitting such a detailed issue.

I have submitted a PR to resolve this issue. See https://github.com/XSAM/otelsql/pull/100

You can use the following pseudocodes to fetch the underlying connection:

```go
type Rawer interface {
	Raw() driver.Conn
}

conn.Raw(func(driverConn interface{}) error {
	if c, ok := driverConn.(Conner) {
		pc := c.Raw().(*stdlib_pgx.Conn).Conn()
		fmt.Printf("%T\n", pc)
        }
})
```

The name `Conn` conflicts with the embed `driver.Conn`, so I use `Raw` as its name.

**Comment by nick-kentik** [comment]
Amazing, thanks for the PR @XSAM!

I've given the branch a whirl in my codebase and it gets the tests passing, so I'd be very happy to see it merged.
